boot.o: boot.S multiboot.h x86_desc.h types.h
interruptlinkage.o: interruptlinkage.S
x86_desc.o: x86_desc.S x86_desc.h types.h
file_system.o: file_system.c file_system.h types.h lib.h systemcalls.h \
  rtc.h terminal.h paging.h keyboard.h x86_desc.h
i8259.o: i8259.c i8259.h types.h lib.h tests.h
idt.o: idt.c idt.h types.h x86_desc.h lib.h keyboard.h terminal.h i8259.h \
  rtc.h interruptlinkage.h systemcalls.h file_system.h paging.h pit.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h keyboard.h terminal.h paging.h rtc.h file_system.h \
  systemcalls.h pit.h
keyboard.o: keyboard.c idt.h types.h x86_desc.h lib.h i8259.h paging.h \
  systemcalls.h file_system.h rtc.h terminal.h keyboard.h
lib.o: lib.c lib.h types.h paging.h
paging.o: paging.c paging.h types.h lib.h
pit.o: pit.c pit.h lib.h types.h x86_desc.h terminal.h i8259.h paging.h \
  systemcalls.h file_system.h rtc.h keyboard.h
rtc.o: rtc.c rtc.h lib.h types.h i8259.h tests.h
systemcalls.o: systemcalls.c systemcalls.h types.h lib.h file_system.h \
  rtc.h terminal.h paging.h keyboard.h x86_desc.h
terminal.o: terminal.c terminal.h types.h lib.h keyboard.h x86_desc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h paging.h file_system.h \
  rtc.h terminal.h
